EVENT_PATTERNS = {
    "breakup": [
        "broke up",
        "breakup",
        "left me",
        "relationship ended",
        "split up",
        "ended things",
        "ex partner",
    ],
    "job_change": [
        "new job",
        "quit job",
        "laid off",
        "fired",
        "started work",
        "job offer",
        "left my job",
    ],
    "loss": [
        "passed away",
        "funeral",
        "grief",
        "family member died",
        "loss of",
        "my mom died",
        "my dad died",
    ],
    "friendship_change": [
        "friendship ended",
        "stopped talking to",
        "drifted from friend",
        "cut off",
        "fell out with",
    ],
    "move": [
        "moved",
        "moved cities",
        "new apartment",
        "relocated",
        "moved home",
    ],
    "wellbeing": [
        "burnout",
        "panic attack",
        "depression",
        "therapy",
        "mental health",
        "hospital",
    ],
}
